admin_login_check:
    path: /admin/login_check

admin_login:
    path: /admin/login
    defaults: { _controller: UserBundle:SecurityAdmin:login }

login_check:
    path: /login_check

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

mremi_contact_form:
    resource: "@MremiContactBundle/Resources/config/routing.xml"

_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

numerogeek_blog:
    resource: "@NumerogeekBlogBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
